In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as map

In [21]:
data_1 = pd.read_csv('/content/control_group.csv' , sep = ';')
data_1.head(10)

,Campaign Name,Date,Spend [USD],# of Impressions,Reach,# of Website Clicks,# of Searches,# of View Content,# of Add to Cart,# of Purchase
0,Control Campaign,1.08.2019,2280,82702.0,56930.0,7016.0,2290.0,2159.0,1819.0,618.0
1,Control Campaign,2.08.2019,1757,121040.0,102513.0,8110.0,2033.0,1841.0,1219.0,511.0
2,Control Campaign,3.08.2019,2343,131711.0,110862.0,6508.0,1737.0,1549.0,1134.0,372.0
3,Control Campaign,4.08.2019,1940,72878.0,61235.0,3065.0,1042.0,982.0,1183.0,340.0
4,Control Campaign,5.08.2019,1835,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Control Campaign,6.08.2019,3083,109076.0,87998.0,4028.0,1709.0,1249.0,784.0,764.0
6,Control Campaign,7.08.2019,2544,142123.0,127852.0,2640.0,1388.0,1106.0,1166.0,499.0
7,Control Campaign,8.08.2019,1900,90939.0,65217.0,7260.0,3047.0,2746.0,930.0,462.0
8,Control Campaign,9.08.2019,2813,121332.0,94896.0,6198.0,2487.0,2179.0,645.0,501.0
9,Control Campaign,10.08.2019,2149,117624.0,91257.0,2277.0,2475.0,1984.0,1629.0,734.0

In [22]:
data__1 = data_1.columns
data__1

Index(['Campaign Name', 'Date', 'Spend [USD]', '# of Impressions', 'Reach',
       '# of Website Clicks', '# of Searches', '# of View Content',
       '# of Add to Cart', '# of Purchase'],
      dtype='object')

In [23]:
data_2 = pd.read_csv('/content/test_group.csv' ,sep = ';')
data_2.head(10)

,Campaign Name,Date,Spend [USD],# of Impressions,Reach,# of Website Clicks,# of Searches,# of View Content,# of Add to Cart,# of Purchase
0,Test Campaign,1.08.2019,3008,39550,35820,3038,1946,1069,894,255
1,Test Campaign,2.08.2019,2542,100719,91236,4657,2359,1548,879,677
2,Test Campaign,3.08.2019,2365,70263,45198,7885,2572,2367,1268,578
3,Test Campaign,4.08.2019,2710,78451,25937,4216,2216,1437,566,340
4,Test Campaign,5.08.2019,2297,114295,95138,5863,2106,858,956,768
5,Test Campaign,6.08.2019,2458,42684,31489,7488,1854,1073,882,488
6,Test Campaign,7.08.2019,2838,53986,42148,4221,2733,2182,1301,890
7,Test Campaign,8.08.2019,2916,33669,20149,7184,2867,2194,1240,431
8,Test Campaign,9.08.2019,2652,45511,31598,8259,2899,2761,1200,845
9,Test Campaign,10.08.2019,2790,95054,79632,8125,2312,1804,424,275

In [24]:
data__2 = data_2.columns
data__2

Index(['Campaign Name', 'Date', 'Spend [USD]', '# of Impressions', 'Reach',
       '# of Website Clicks', '# of Searches', '# of View Content',
       '# of Add to Cart', '# of Purchase'],
      dtype='object')

In [25]:
data_1.columns = ['campaign name' , 'date' , 'sales', "number of impressions" ,'reach' , 'number of clicks' , 'number of searches', 'number of view content' , 'number of add to cart' , 'number of purchase' ]
data_2.columns = ['campaign name' , 'date' , 'sales', "number of impressions" ,'reach' , 'number of clicks' , 'number of searches', 'number of view content' , 'number of add to cart' , 'number of purchase' ]

In [26]:
print(data_1 .columns)
print(data_2.columns)

Index(['campaign name', 'date', 'sales', 'number of impressions', 'reach',
       'number of clicks', 'number of searches', 'number of view content',
       'number of add to cart', 'number of purchase'],
      dtype='object')
Index(['campaign name', 'date', 'sales', 'number of impressions', 'reach',
       'number of clicks', 'number of searches', 'number of view content',
       'number of add to cart', 'number of purchase'],
      dtype='object')

In [27]:
print(data_1.isnull().sum())

campaign name             0
date                      0
sales                     0
number of impressions     1
reach                     1
number of clicks          1
number of searches        1
number of view content    1
number of add to cart     1
number of purchase        1
dtype: int64

In [28]:
print(data_2.isnull().sum())

campaign name             0
date                      0
sales                     0
number of impressions     0
reach                     0
number of clicks          0
number of searches        0
number of view content    0
number of add to cart     0
number of purchase        0
dtype: int64

In [29]:
# replace null values with mean
data_1['reach'].fillna(data_1['reach'].mean(), inplace = True)
data_1['number of impressions'].fillna(data_1['number of impressions'].mean(), inplace = True)

<ipython-input-29-f67989004853>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_1['reach'].fillna(data_1['reach'].mean(), inplace = True)
<ipython-input-29-f67989004853>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_1['number of impressions'].fillna(data_1['number of impressions'].mean(), inplace = True)

In [30]:
data_1['number of clicks'].fillna(data_1['number of clicks'].mean(), inplace = True)
data_1['number of searches'].fillna(data_1['number of searches'].mean(), inplace = True)
data_1['number of add to cart'].fillna(data_1['number of add to cart'].mean(), inplace = True)
data_1['number of view content'].fillna(data_1['number of view content'].mean(), inplace = True)
data_1['number of purchase'].fillna(data_1['number of purchase'].mean(), inplace = True)

<ipython-input-30-8eeb29186739>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_1['number of clicks'].fillna(data_1['number of clicks'].mean(), inplace = True)
<ipython-input-30-8eeb29186739>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_1['number of searches'].fillna(data_1['number of searches'].mean(), inplace = True)
<ipython-input-30-8eeb29186739>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_1['number of add to cart'].fillna(data_1['number of add to cart'].mean(), inplace = True)
<ipython-input-30-8eeb29186739>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_1['number of view content'].fillna(data_1['number of view content'].mean(), inplace = True)
<ipython-input-30-8eeb29186739>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_1['number of purchase'].fillna(data_1['number of purchase'].mean(), inplace = True)

In [31]:
data_1.describe()

,sales,number of impressions,reach,number of clicks,number of searches,number of view content,number of add to cart,number of purchase
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
mean,2288.433333,109559.758621,88844.931034,5320.793103,2221.310345,1943.793103,1300.000000,522.793103
std,367.334451,21311.695472,21452.627592,1726.803732,851.025795,764.021907,400.371207,181.810508
min,1757.000000,71274.000000,42859.000000,2277.000000,1001.000000,848.000000,442.000000,222.000000
25%,1945.500000,95191.250000,75300.250000,4122.250000,1629.250000,1249.000000,942.500000,375.500000
50%,2299.500000,112368.000000,91418.000000,5272.396552,2340.000000,1979.500000,1319.500000,506.000000
75%,2532.000000,121259.000000,101958.750000,6609.500000,2655.000000,2360.500000,1638.000000,663.250000
max,3083.000000,145248.000000,127852.000000,8137.000000,4891.000000,4219.000000,1913.000000,800.000000

In [32]:
data_1['date'] = pd.to_datetime(data_1['date'],format='%d.%m.%Y')
data_2['date'] = pd.to_datetime(data_2['date'],format='%d.%m.%Y')

In [33]:
data_1['date']

0    2019-08-01
1    2019-08-02
2    2019-08-03
3    2019-08-04
4    2019-08-05
5    2019-08-06
6    2019-08-07
7    2019-08-08
8    2019-08-09
9    2019-08-10
10   2019-08-11
11   2019-08-12
12   2019-08-13
13   2019-08-14
14   2019-08-15
15   2019-08-16
16   2019-08-17
17   2019-08-18
18   2019-08-19
19   2019-08-20
20   2019-08-21
21   2019-08-22
22   2019-08-23
23   2019-08-24
24   2019-08-25
25   2019-08-26
26   2019-08-27
27   2019-08-28
28   2019-08-29
29   2019-08-30
Name: date, dtype: datetime64[ns]

In [34]:
a_b = data_1.merge(data_2 , how ='outer').sort_values(['date'])
ab_data = a_b.reset_index(drop = True)
ab_data.head(10)

<ipython-input-34-0999e25e3f32>:1: UserWarning: You are merging on int and float columns where the float values are not equal to their int representation.
  a_b = data_1.merge(data_2 , how ='outer').sort_values(['date'])

,campaign name,date,sales,number of impressions,reach,number of clicks,number of searches,number of view content,number of add to cart,number of purchase
0,Control Campaign,2019-08-01,2280,82702.000000,56930.000000,7016.000000,2290.000000,2159.000000,1819.0,618.000000
1,Test Campaign,2019-08-01,3008,39550.000000,35820.000000,3038.000000,1946.000000,1069.000000,894.0,255.000000
2,Control Campaign,2019-08-02,1757,121040.000000,102513.000000,8110.000000,2033.000000,1841.000000,1219.0,511.000000
3,Test Campaign,2019-08-02,2542,100719.000000,91236.000000,4657.000000,2359.000000,1548.000000,879.0,677.000000
4,Control Campaign,2019-08-03,2343,131711.000000,110862.000000,6508.000000,1737.000000,1549.000000,1134.0,372.000000
5,Test Campaign,2019-08-03,2365,70263.000000,45198.000000,7885.000000,2572.000000,2367.000000,1268.0,578.000000
6,Control Campaign,2019-08-04,1940,72878.000000,61235.000000,3065.000000,1042.000000,982.000000,1183.0,340.000000
7,Test Campaign,2019-08-04,2710,78451.000000,25937.000000,4216.000000,2216.000000,1437.000000,566.0,340.000000
8,Control Campaign,2019-08-05,1835,109559.758621,88844.931034,5320.793103,2221.310345,1943.793103,1300.0,522.793103
9,Test Campaign,2019-08-05,2297,114295.000000,95138.000000,5863.000000,2106.000000,858.000000,956.0,768.000000

In [35]:
testing  = ab_data.to_csv('testing.csv')

In [36]:
avg = ab_data.groupby('campaign name') ['sales'].mean()
print(avg)

campaign name
Control Campaign    2288.433333
Test Campaign       2563.066667
Name: sales, dtype: float64